### ISSUE TITLE
GCC packages available?

### ISSUE THREAD

**Issue by lasote** [hklabbers/conan-mysqlclient#3]
Do you plan to generate GCC packages for linux? Do you need support for doing it with travis ci?
Thanks

**Comment by hklabbers** [comment]
Yes, I tried with travis. Unfortunately I run into an error. I have a CONAN_PASSWORD env variable. See the log.
Setting environment variables from repository settings
$ export CONAN_PASSWORD=[secure]
Setting environment variables from .travis.yml
$ export CONAN_UPLOAD=1
$ export CONAN_REFERENCE="mysqlclient/6.1.6"
$ export CONAN_USERNAME="hklabbers"
$ export CONAN_CHANNEL="ci"
$ export CONAN_TOTAL_PAGES=1
$ export CONAN_CURRENT_PAGE=1
$ export CONAN_GCC_VERSIONS=4.8
$ export CONAN_USE_DOCKER=1
|
|
|
|
/usr/bin/cmake -E cmake_progress_start /home/conan/project/test_package/build/9056a4567a959a72eafffd6616532bf214cc1e5d/CMakeFiles 0
MySQL client version: 6.1.6
############## CONAN PACKAGE TOOLS ######################
INFO: *******\* RUNNING UPLOAD COMMAND *********\* 
conan upload mysqlclient/6.1.6@hklabbers/stable --all --force 
#########################################################
Change 'conan.io' user from None (anonymous) to hklabbers
ERROR: There is no local conanfile exported as mysqlclient/6.1.6@hklabbers/stable
The command "./.travis/run.sh" exited with 0.
Done. Your build exited with 0.

For Macos and windows (appveyor) it is working fine. Have you a clue? Your help is appreciated. 

Cheers!

**Comment by lasote** [comment]
I think the problem is the lowercases in .travis.yml:

```
env:
  global:
    - CONAN_UPLOAD=1
    - CONAN_REFERENCE="mysqlclient/6.1.6"
```

Should be: CONAN_REFERENCE="MySQLClient/6.1.6" because it's case sensitive.

Hope it helps!

**Comment by hklabbers** [comment]
Changed the line in .travis.yml. But conan.io has issues, it reports 502 Bad Gateway. So I will try to rebuild tomorrow. When it works, I will close this issue.

**Comment by hklabbers** [comment]
GCC packkages for linux are generated and uploaded. ~~Is it possible to remove the packages with lowercase names?~~ Done, removed the packages with lowercase names.
